version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: suse_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: suse_db
      OSS_CLIENT_URL: http://oss-client:5002
    depends_on:
      mysql:
        condition: service_healthy
      oss-client:
        condition: service_started
    ports:
      - "5001:5001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      retries: 5
      start_period: 10s

  oss-client:
    build:
      context: ./oss-client
      dockerfile: Dockerfile
    environment:
      OSS_ACCESS_KEY_ID: LTAI5tBBgFYxQKaEF3ZQ2y9W
      OSS_ACCESS_KEY_SECRET: i683yLu5t8FvaqRoci3tAOJjUEbKKN
      OSS_ENDPOINT: https://oss-cn-hongkong.aliyuncs.com
      OSS_BUCKET_NAME: for-kody-image
    ports:
      - "5002:5002"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 10s
      retries: 5
      start_period: 10s

  jaeger:
    image: jaegertracing/all-in-one:1.58
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "6831:6831/udp"  # Jaeger agent
      - "16686:16686"    # Jaeger UI
      - "9411:9411"      # Zipkin compatible endpoint
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: