apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: registry.cn-hangzhou.aliyuncs.com/kody_poc/suse-backend:latest
        env:
        - name: MYSQL_HOST
          value: susemysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: rancher
        - name: MYSQL_DB
          value: suse_db
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: backend
  type: ClusterIP