apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql_sts.yaml
  - mysql_svc.yaml
  - mysql_cm.yaml
  - mysql_pvc.yaml
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - oss-client-deployment.yaml
commonLabels:
  app.kubernetes.io/part-of: suse-app