apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namespace: dev
namePrefix: dev-
patchesStrategicMerge:
- patch-frontend.yaml
- patch-backend.yaml
- patch-oss-client.yaml
commonLabels:
  environment: dev